### ISSUE TITLE
Avoid saving on partials

### ISSUE THREAD

**Issue by noAlvaro** [alexnj/SublimeOnSaveBuild#11]
Hi,

Just tried to manage a way around SASS partials (the files starting with "_"), so as to avoid building the project unnecessarily. So I've adjusted the ```filename_filter``` setting, leaving it as the following:

```
{
    "filename_filter": "\\.(css|js|sass|less)|^[^_].+\\.(scss)",
    "build_on_save": 1
}
```

I've tested the new regex in some editors and it is working fine. But SublimeOnSaveBuild still compiling archives with the initial "_" character.

_Am I missing something?_

Thank you.

**Comment by alexnj** [comment]
The extension list is only illustrative. Also, I'm not sure if modifying partials should avoid a build - since any SCSS that depends on it might be invalid at that point. Or perhaps I'm missing the point. 

Closing the issue, assuming @jawinn's solution works.
