### ISSUE TITLE
Respect the "working_dir" setting

### ISSUE THREAD

**Issue by kofalt** [alexnj/SublimeOnSaveBuild#12]
A project that uses the `working_dir` setting will not work as expected with OnSaveBuild.

Example project configuration snippet:
```json
"build_systems":
[
	{
		"name": "CouchApp Push",
		"working_dir": "../myFolder",
		"cmd": ["couchapp", "push", "local"]

		"windows": {
			"cmd": ["couchapp.bat", "push", "local"]
		}
	}
]
```

Here I have several sublime-project files stored in a single directory for convenience, and this relative folder reference will run fine without the plugin installed, and will fail when the plugin is installed. Moving the sublime-project file to the same difrectory and removing the `working-dir` setting fixes the issue.

**Comment by alexnj** [comment]
Cleaning up issues list,

**Comment by kofalt** [comment]
![5oaj6dr](https://cloud.githubusercontent.com/assets/265071/6095144/169490d0-af13-11e4-8939-98442d0b619e.gif)

**Comment by alexnj** [comment]
:) 

I wasn't sure if you were able to reach a solution - the issue has been open for a couple of years (my bad, my bad; I've not been looking at the project for a long while!). With some free time at hand, I was going through the pending issues to see if there's any I can solve now, and came across this. If you are still facing the issue (shamelessly asking!) I'd be glad to help.

**Comment by kofalt** [comment]
Haha honestly, I just wanted to GIF the thread.

I stopped using this plugin awhile back ([reflex](https://github.com/cespare/reflex#a-simple-example) is a lovely utility) so I don't mind :D

**Comment by alexnj** [comment]
Cheers!
