### ISSUE TITLE
please add execution delay

### ISSUE THREAD

**Issue by jitin-sameer** [alexnj/SublimeOnSaveBuild#15]
I have a couple of ST2 plugins which execute on "save action" to do code cleanup and preprocessing. As a result, SublimeOnSaveBuild frequently build the projects before all the code cleanup/preprocessing is done by other plugins and the built files either fail or they are incomplete.

I request officially adding a small delay like 50 ms before executing build. I've adding 50ms execution delay for my local files. If you want, I can provide a patch.

**Comment by alexnj** [comment]
Ideally you should be using a single on-save build script, that does any processing required, sequentially.
