### ISSUE TITLE
Not working with jsx

### ISSUE THREAD

**Issue by cperryk** [alexnj/SublimeOnSaveBuild#24]
I have a build system set up to compile React jsx files to regular js. The selector is is <code>source.js.jsx</code>. When I've set the "Build System" preference to "Automatic" and I'm on the file and hit command+b, the compiled code builds as expected. However, saving the file does nothing — SublimeOnSaveBuild doesn't appear to work for it, and I can't figure out why.

To reproduce:
1. Install the JSX syntax
2. Create a build system in which the selector is source.js.jsx (the command can do anything really, like [just echo "test"](https://www.dropbox.com/s/vbpqioelja9nr7m/Screenshot%202015-01-26%2014.57.17.png?dl=0))
3. Open a file and set its syntax to JSX
4. Save the file
5. Try to view build results — you may not be able to, or the results pane will not show any new information because it seems the build never runs
6. Hit cmd+b, or select Tools > Build. Results will now appear

**Comment by alexnj** [comment]
`.jsx` is not part of the standard set of file name filters. Have you configured this via `filename_filter` setting? 

`"filename_filter": "\\.(css|js|sass|less|scss|jsx)$",`

**Comment by cperryk** [comment]
Thanks! That works. For reference, I've set my build system to "automatic," and my here's my SublimeOnSaveBuild config:
```
{
    "filename_filter": "\\.(css|js|sass|less|scss|cson|jsx)$"
}
```

And here's my build system:
```
{
	"cmd": ["jsx", "--watch", "-x", "jsx", "./", "./"],
	"selector":"source.js.jsx"
}
```
