### ISSUE TITLE
disable saving all the opened files

### ISSUE THREAD

**Issue by ctf0** [alexnj/SublimeOnSaveBuild#32]
currently the plugin saves all the opened tabs even if i removed the file extensions from the plugin settings

**Comment by lspitzner** [comment]
that happens on build; not really anything this plugin can do about this. or am i missing something?

**Comment by ctf0** [comment]
build system save the current file by default, NOT all opened files, u can try ur self.

**Comment by lspitzner** [comment]
tried; in my project it saved a non-selected tab on build (triggered manually, not via this plugin). also, this plugin's code does not seem to do anything saving-related. but then i am not the author and certainly no sublime (dev) expert.
