### ISSUE TITLE
Broken on Sublime Text 3

### ISSUE THREAD

**Issue by mockingbird87** [alexnj/SublimeOnSaveBuild#35]
Since this morning august 5 2016. Building on save in Sublime Text 3 doesnt seem to be working anymore

**Comment by breams** [comment]
Can confirm this isn't working for me also and I'm trying to work out why. Will update if I come across anything. I wasn't aware of any changes in my setup that had been working perfectly until today.

**Comment by mockingbird87** [comment]
I managed to uninstall the last update and manually installed the previous version. GIT version control FTW!

**Comment by breams** [comment]
I've found the bug and am forking and doing a pull request as we speak.

**Comment by breams** [comment]
[This pull request (#36)](https://github.com/alexnj/SublimeOnSaveBuild/pull/36) should solve the problem

**Comment by alexnj** [comment]
I went ahead and reverted the PR that broke backward compatibility. My sincere apologies for not doing a thorough evaluation of that PR before merging. @breams, thanks so much for chiming in with a PR to fix the issue. 

There's more info as to why this broke and why it's being rolled back on #34. Please feel free to chime in.

Please let me know if the issue continues after updating to the latest (the version with reverted PR). Thanks so much.

**Comment by hyouuu** [comment]
I'm with ST3 build 3162, and save doesn't trigger anything - anyone else has the same issue?

**Comment by hyouuu** [comment]
Nevermind - didn't update "filename_filter" - btw in ST3 all settings are living in the same file, so probably better adding a on_save_build_ prefix :) Thanks for the package!
